add multiple scripts and update setup script

diff --git a/bin/connect-to-kyk b/bin/connect-to-kyk
--- a/bin/connect-to-kyk
+++ b/bin/connect-to-kyk
@@ -1,36 +1,34 @@
-#!/usr/bin/env python
+#!/usr/bin/env bash
 
-import requests
-import sys
+source "/home/lem0n/.dotfiles/configuration/wifi/credentials"
 
-headers = {
-    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
-    'Accept-Language': 'en-GB;q=0.6',
-    'Cache-Control': 'no-cache',
-    'Connection': 'keep-alive',
-    'Origin': 'https://wifi.gsb.gov.tr',
-    'Pragma': 'no-cache',
-    'Referer': 'https://wifi.gsb.gov.tr/login.html',
-    'Sec-Fetch-Dest': 'document',
-    'Sec-Fetch-Mode': 'navigate',
-    'Sec-Fetch-Site': 'same-origin',
-    'Sec-Fetch-User': '?1',
-    'Sec-GPC': '1',
-    'Upgrade-Insecure-Requests': '1',
-    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 11_12) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4880.113 Safari/537.36',
-}
+res=$(curl \
+    -X POST \
+    -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
+    -H 'Accept-Encoding: gzip, deflate, br' \
+    -H 'Accept-Language: en-GB;q=0.6' \
+    -H 'Cache-Control: no-cache' \
+    -H 'Connection: keep-alive' \
+    -H 'Cookie: JSESSIONID=F4135E195673816E730A89AF0D93CF4F; BIGipServerpool_cps_portal=!sErpKFnxV6EOrIYvP4O/pWibSlDABrOln4wvI2jxErnQzczRm8Fd9lrYtbWTL0EaG97FvAXw14JfshTFismyrXJrAgjo8ioMgjKyFWKf' \
+    -H 'Origin: https://wifi.gsb.gov.tr' \
+    -H 'Pragma: no-cache' \
+    -H 'Referer: https://wifi.gsb.gov.tr/login.html' \
+    -H 'Sec-Fetch-Dest: document' \
+    -H 'Sec-Fetch-Mode: navigate' \
+    -H 'Sec-Fetch-Site: same-origin' \
+    -H 'Sec-Fetch-User: ?1' \
+    -H 'Sec-GPC: 1' \
+    -H 'Upgrade-Insecure-Requests: 1' \
+    -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_12) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4880.113 Safari/537.36' \
+    -w "%{http_code}" \
+    -o /dev/null \
+    -d "{'j_username': '$KYK_WIFI_IDENTITY', 'j_password': '$KYK_WIFI_PASSWORD', 'submit': 'Login'}" \
+    -s -L "https://wifi.gsb.gov.tr/j_spring_security_check")
 
-data = {
-    'j_username': '***REMOVED***',
-    'j_password': '***REMOVED***',
-    'submit': 'Login',
-}
-
-response = requests.post('https://wifi.gsb.gov.tr/j_spring_security_check', headers=headers, data=data)
-
-if response.status_code == 200:
-    print("LOGGED IN")
-    os.exit(0)
-else:
-    print("ERROR")
-    sys.exit(1)
+if [[ "$res" -eq 200 ]]; then
+    echo "LOGGED IN"
+    exit 0
+else
+    echo "ERROR"
+    exit 1
+fi
